// Build the Supabase Edge Function artifact: bundle OUR code into one ESM
// file (Deno cannot resolve the repo's Node-style ".js" relative imports),
// keep npm deps external, and generate a deno.json import map pinning each
// dep to the exact installed version via npm: specifiers.
import { build } from "esbuild";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const serverDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.resolve(serverDir, "../supabase/functions/brian");
mkdirSync(outDir, { recursive: true });

// Runtime deps reachable from the edge entry. @hono/node-server is Node-only
// and deliberately absent.
const deps = [
  "hono",
  "@hono/mcp",
  "@modelcontextprotocol/sdk",
  "pg",
  "openai",
  "bcryptjs",
  "jsonwebtoken",
  "zod",
];

const version = (dep) =>
  JSON.parse(readFileSync(path.join(serverDir, "node_modules", dep, "package.json"), "utf8")).version;

const imports = {};
for (const dep of deps) {
  const v = version(dep);
  imports[dep] = `npm:${dep}@${v}`;
  imports[`${dep}/`] = `npm:/${dep}@${v}/`; // subpath imports (e.g. sdk/server/mcp.js)
}

await build({
  entryPoints: [path.join(serverDir, "src/edge/entry.ts")],
  bundle: true,
  format: "esm",
  platform: "node",
  target: "esnext",
  packages: "external",
  define: { __BUILD_ID__: JSON.stringify(new Date().toISOString()) },
  minify: true,     // artifact is generated + shipped inline to the deploy API
  keepNames: true,  // error classes are matched by name in logs
  sourcemap: false,
  outfile: path.join(outDir, "index.js"),
  banner: { js: "// AUTO-GENERATED by `npm run edge:build` — do not edit." },
});

writeFileSync(path.join(outDir, "deno.json"), JSON.stringify({ imports }, null, 2) + "\n");
console.log(`bundled → ${path.relative(process.cwd(), path.join(outDir, "index.js"))}`);
